name: Actualizador de Lista IPTV

on:
  schedule:
    - cron: '0 */3 * * *' # Se ejecuta cada 3 horas
  workflow_dispatch:      # Botón para ejecutarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        pip install selenium webdriver-manager
        
    - name: Ejecutar extractor
      run: python extractor_pro.py

    - name: Guardar cambios
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lista_final.m3u
        git commit -m "Lista actualizada automáticamente" || echo "Sin cambios"
        git push
